### ISSUE TITLE
Production migration checklist

### ISSUE THREAD

**Issue by konklone** [18F/18f.gsa.gov#171]
Outstanding development tickets:
- [ ] #159 - Test again on IE8.
- [ ] #164 - Various design fixes.
- [ ] OG/Twitter metadata
- [ ] `rel=canonical`

When those are done and we're ready to move the site to production, here's what we'll need to do:
- [ ] Install new production SSL certificate to our new server, verify configuration.
- [ ] Merge `staging` into `production`. This will not update our _current_ live site automatically.
- [ ] Update `production` code on new server, manually.
- [ ] Update our Tumblr blog to set up redirects to our new posts.
- [ ] Redirect the root to our 
- [ ] Update DNS for `18f.gsa.gov` to point to the new server. 
- [ ] Run the hookshot daemon for the production site.
- [ ] Create a webhook inside of GitHub that points to the production site.
- [ ] Verify webhook works. Verify site looks good.
- [ ] :fireworks:
