### ISSUE TITLE
Enhance press content

### ISSUE THREAD

**Issue by gboone** [18F/18f.gsa.gov#1893]
The content on /press has two main problems:
1. It's stale. We have projects on there we're not involved with anymore, and it doesn't accurately explain how we actually work, our structure, our business model, etc.
2. We don't know if it accurately helps journalists looking for information about 18F. More research should be done to discover what reporters are looking for in a press page and whether the content here is useful to them.

Addressing these two issues will result in better accuracy in reporting on 18F and our projects in the press as well as fewer requests for basic information.

**Comment by awfrancisco** [comment]
Might be also interesting to use the press page to MVP a solution for some of the needs the Dashboard would fill - such as major projects in progress, explanation of project stages, contact info for BUs/projects/topics.

**Comment by coreycaitlin** [comment]
Next steps:

- [ ] Content inventory of the press page
- [ ] Content testing
- [ ] Research to find out whether journalists look for press pages

**Comment by coreycaitlin** [comment]
Projects on the press page:

- [ ] myUSCIS
- [ ] betaFEC --> project page #1967 
- [ ] College Scorecard --> project page #2104 
- [ ] Draft U.S. Web Design Standards
- [ ] analytics.usa.gov
- [ ] cloud.gov --> project page #2068 
- [ ] DoL Wage and Hour Division Field Operations Handbook
- [ ] RFP Ghostwriting with CA --> project page #2069 
- [ ] Every Kid in a Park --> project page #2105 
- [ ] USEITI --> project page #2022 
- [ ] CALC and Discovery

**Comment by coreycaitlin** [comment]
I've also opened an issue for the "about" content on this page: #2186

**Comment by coreycaitlin** [comment]
Non-project parts of this page are:

- [ ] intro - move to top of about page
- [ ] media contact link - move to press section of about
- [ ] what 18F has accomplished - see project pages
- [ ] 18F projects adapted by other organizations
- [ ] 18F's relationship with USDS - no need to move?
- [ ] basic info on history - move to history section of about
- [ ] how 18F works - move to funding section of about / also How we work and Hire 18F
- [ ] how 18F is funded - move to funding section of about

**Comment by coreycaitlin** [comment]
@awfrancisco ^^ here's my mini-content-inventory of the /press page — any thoughts about whether we should keep the "18F projects adapted by other orgs" section, and where to put it?

Also, if you have concerns about any of the notes about other sections of the page, just let me know!

**Comment by awfrancisco** [comment]
Looks good. The adapted projects would ideally go on some kind of /open page about transparency and open source code. Also, any comprehensive list of adaptations would be extremely long. I think it's fine to drop for now, and we should remember it as a feature to incorporate into future pages. Doesn't seem like this info has been a big user need.

**Comment by afeld** [comment]
@awfrancisco I refer (people to it) regularly. Agreed the press page probably isn't the best place, but would like for it to be _somewhere_.

/cc @gbinal @konklone

**Comment by konklone** [comment]
Even if it's not a well-trafficked page, it's an important story and reference for our stakeholders. In this case, the user need may primarily be internal, but it's real.

That said, @afeld, @gbinal, do you have an idea of the best person/group to "own" keeping the page up to date?

**Comment by afeld** [comment]
I've been updating the `projects adapted by other organizations` (as part of #wg-opensource), and am happy to continue doing so.

**Comment by awfrancisco** [comment]
Thanks for the feedback. This might be better as part of an "our work" page rather than a press page.

**Comment by konklone** [comment]
@awfrancisco Totally.

**Comment by coreycaitlin** [comment]
I think the next actions here (for press resources specifically) are...

- [ ] Write any content we want in the "Press" section of the about page
- [ ] Identify and package any files we want to include on this page
- [ ] Put that stuff on the page

Assigning to @awfrancisco, but I'm happy to help if you want to pair!

We'll split off the Our Work / What we deliver work to #2194

**Comment by awfrancisco** [comment]
I think this section should include a number of images press can use for stories and the 18F and GSA logos. What do you all think is the best way to do that? My two ideas are a list of direct downloads with brief descriptions right on the press page or a link to a folder in the 18f.gsa.gov repo with the files and a README with more info (captions, credits) for each photo. What do you all think?  I think we might want to have about a dozen images they could download.

**Comment by coreycaitlin** [comment]
I think either could work, and a list of downloads is probably a little easier for some less-technical press folks.

**Comment by awfrancisco** [comment]
All the press content for this round is up on dev. @coreycaitlin we good to close?
