### ISSUE TITLE
Add DOI Job Posting to Join 18F

### ISSUE THREAD

**Issue by rooneywp** [18F/18f.gsa.gov#2463]
TTS Talent is engaged with DOI on a recruitment project. In support of this project, we need to post the DOI job on our join page so that we can collect applications. This is billable work, so any hours spent on this issue should be recorded in Tock. **Tock Code: 465 - Talent / DOI ONRR / EITI FY17**

**Issue:** Need a way to post the DOI job on our join page.

**Tasks:**
- [ ] Add language to join page that differentiates the DOI job as NOT 18F/TTS
- [ ] Add a file/page that contains all of the job information and a link to the application form
- [ ] Remove content once job is closed

**Comment by rooneywp** [comment]
@gboone Based on our previous discussion about how job postings should be handled, I thought we could use google docs and publish to the web. Unfortunately, publishing a doc to the web still requires GSA login to access. 

![image](https://user-images.githubusercontent.com/13383307/27602757-bfe7e894-5b28-11e7-9f86-c1e87ff98e36.png)

We will need to figure out the workflow for job postings for this and the new roles that we will be posting for TTS. Hopefully, I'm just doing something wrong with publishing because that would have worked very well :(

**Comment by elainekamlley** [comment]
@rooneywp Greg is out on PTO till the 5th. What is the timeline and would you need support with this before then?

**Comment by elainekamlley** [comment]
Posted with #2473
