### ISSUE TITLE
Speaker request blurb on site

### ISSUE THREAD

**Issue by Dahianna** [18F/18f.gsa.gov#2693]
Recently we've received requests for staff to participate in panels or speak at events. Unfortunately, we were unable to fulfill these requests due to either lack of information about the event or not having enough time to process the speaker request through TTS and OSC. These situations can make us look uninterested or unwilling, which could impact our relationship with the event hosts.

By adding a paragraph with guidance about our speaking request process to the site (press, contact or both), event hosts could better determine if we are a good fit for their event, and able to process the request on time

**Tasks**
- [ ] Draft content for the paragraph
- [ ] Determine where to add it on the site
- [ ] Test effectiveness of the paragraph
