### ISSUE TITLE
USWDS Upgrade Action Plan Roadmap

### ISSUE THREAD

**Issue by lsgitter** [18F/18f.gsa.gov#3103]
## Roadmap Summary

- SASS errors when compiling
- Work on font sizing
- Updating the new design

## To Do (to get all of 18f.gsa.gov back to "normal")

- [x] SASS errors when compiling @heymatthenry 
- Reviewing higher level components that can plug and play from V2 into 18f.gsa.gov
  - [x] Identify possible adhoc custom code / components @apburnes 
  - [x] Identify any current repetition/duplication in UI components @apburnes 
  - [x] Map adhoc to USWDS v2 @apburnes 
  - [x] Scrub/remove adhoc custom code / components *tbd - reassess next sprint*

## First To Do on Redesign
- [ ] Add updated `home.html`

**Comment by Dahianna** [comment]
Fixed with #3097
