### ISSUE TITLE
Guides page update review

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/18f.gsa.gov#3367]
## Section Header
See #3374

## Guide Links
![image](https://user-images.githubusercontent.com/52677065/110020905-1b7f6700-7cf8-11eb-8430-70afc6e4f8c7.png)
- Some of the links (Accessibility, agile, content, design methods, product) have the text in `#00547a` some in `#1C304A`. They should all be in `#1C304A` ( `#00547a` is not a brand color)
- The caret should be center aligned with the text
- The caret should be smaller and slightly thinner ~ the x-height of the text 
Existing site: 
![image](https://user-images.githubusercontent.com/52677065/110021225-79ac4a00-7cf8-11eb-94ea-1bb10dc4c808.png)
Branch:
![image](https://user-images.githubusercontent.com/52677065/110021245-816bee80-7cf8-11eb-9574-a67939ce21f7.png)

## Call to Action
![image](https://user-images.githubusercontent.com/52677065/110021686-0f47d980-7cf9-11eb-87b4-876bdabf4128.png)
- The background color is `#162e51` which is not a brand color. Should be `#1C304A`
- Text should be large (~2rem) (looks like this is isn’t getting compiled correctly: 
![image](https://user-images.githubusercontent.com/52677065/110021840-3c948780-7cf9-11eb-8508-ebcf5ad044ca.png)
- Button should be have background color `#00CFFF` and font-color `#1C304A`. 
- Button currently disappears into the background on hover:
![image](https://user-images.githubusercontent.com/52677065/110022037-76fe2480-7cf9-11eb-92cc-cb1faff77bdd.png)

## Summary Checklist 
**Section Header**
- Changed based on discussion in #3374 

**Guide Links**
- [ ] All links are `#1C304A` and `#046B99` on hover
- [ ] Caret icon is vertically centered with the text
- [ ] Caret icon is ~ the height of the letter "x"  in the the text

**CTA**
- [ ] Background color should be `#1C304A`  
- [ ] Text is lg size
- [ ] Button has background color `#00CFFF` and font-color `#1C304A`.  (can follow the [ACCENT COOL COLOR ](https://designsystem.digital.gov/components/button/)example for states)

**Comment by igorkorenfeld** [comment]
Turns out the font issue maybe due to anti-aliasing, adding in `-webkit-font-smoothing: antialiased` helps the font not look so chunky.

**Comment by lauraGgit** [comment]
@igorkorenfeld re:
> Looking at other pages on the current site, I realized the H1 ought to be smaller. as well, as it's being used as a kind of pre-header text. Size should be ~2.3 rem, so something like lg should work?

I feel a bit funny about the site using an h1 in a non-header way- I was kind of wondering if we might update that?

**Comment by igorkorenfeld** [comment]
Sure, can you say more about that?

**Comment by igorkorenfeld** [comment]
@lauraGgit I pulled the section header into a separate issue since it affects multiple pages. Now in #3374 3374
