### ISSUE TITLE
Project Page Update Review 

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/18f.gsa.gov#3372]
## Page Header
See #3374

## Text
Section pre-titles (Background, & Approach) should be in smallcaps (or simulating smallcaps).
- Section pre-titles should be bold
- Section pre-titles should be ~14px, so something like `2xs` should work
- Section pre-titles should be more closely grouped with the title below them, so that there is more space above them than below. That means 6 units above (48px) and 0.5 units below (4px)

## Related Blog Posts
- "Related blog posts" has too much padding on top. Could we reduce to 5 units?
- "See all posts..." link should be on the same line as “Related Blog Posts” and  right aligned with the 3rd column
- The H4 titles are `#00547A` and should be be `#046B99` 
- Read more color is `#00547A` and should be be `#046B99` 
- The caret on read more should be smaller and vertically centered with the x height of the text. 
Current site: 

![image](https://user-images.githubusercontent.com/52677065/110134918-eb899f80-7d9b-11eb-9025-8576724d250b.png)

Branch: 
![image](https://user-images.githubusercontent.com/52677065/110134868-ddd41a00-7d9b-11eb-8edb-b08cc14f4acb.png)

## Sidebar
The current sidebar is styled like a sub-navigation menu, but serves a different function here. It lists out project details and external links. Could we style it different than a sidenav? Here is what I am thinking (this is similar to the side links on Tock):

![image](https://user-images.githubusercontent.com/52677065/110135035-0d832200-7d9c-11eb-8f79-b1150c6bfc6f.png)
- Increase space above the H5s to 1 unit
- Agency name also has line-height 1.6
- Unindent the links
- Remove grey borders
- Remove grey background on hover
- Give the links regular link styling (i.e. color: `#046B99` and underlined)

## Call to Action
![image](https://user-images.githubusercontent.com/52677065/110135228-428f7480-7d9c-11eb-8eee-596de446af68.png)
- Similar to the text issue in #3367 the text has some extra weight to it. Let's add letterspacing of `ls(1)` and if possible use font-smoothing
- Similar to the #3367 button is difficult to see on this background, let's use background color `#00CFFF` and font-color `#1C304A`.

## Summary Checklist
**Page Header**
- [x] Changed based on #3374 

**Text**
- [ ] Section pre-titles are bold
- [ ] Section pre-titles are ~ `2xs` 
- [ ] Section pre-titles have 6 units of space above (48px) and 0.5 units below (4px)

**Related Blog Posts**
- [ ] "Related blog posts" has 5 units of space above?
- [ ] "See all posts..." link is vertically aligned “Related Blog Posts” and right aligned with the 3rd column
- [ ] The H4 titles are `#00547A` and should be be `#046B99` 
- [ ] Read more color is `#00547A` and should be be `#046B99` 
- [ ] The caret on read more is smaller and vertically centered with the x height of the text. 

**Sidebar**
- [ ] H5s have 1 unit of space above
- [ ] Agency name has line-height 1.6 (i.e. matches line-height of other text in sidenav)
- [ ] Links are unindented 
- [ ] No grey borders above or below links
- [ ] No grey background on link hover
- [ ] Links have regular link style,  color: `#046B99` and underlined

**CTA**
- [ ] Text has letterspacing `ls(1)`
- [ ] Look into font-smoothing
- [ ] Button has background color `#00CFFF` and font-color `#1C304A`.  (can follow the [ACCENT COOL COLOR ](https://designsystem.digital.gov/components/button/)example for states)

**Comment by lauraGgit** [comment]
@igorkorenfeld seeing a lot of places where you'd like to bump down the default padding of a `usa-section` from 8 units down to 5 units. Should we just go and make that a global?

**Comment by lauraGgit** [comment]
Also, I love your checklists so much, would you be able to add one for the related post tasks?

**Comment by igorkorenfeld** [comment]
Yes please, let's make it global

And yes definitely, that was an oversight so thanks for catching that.

**Comment by igorkorenfeld** [comment]
Added the checklist!

**Comment by lauraGgit** [comment]
You're the best! thx
