### ISSUE TITLE
What we deliver page review

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/18f.gsa.gov#3376]
## Intro Hero
Please see #3374 

## Intro text

![image](https://user-images.githubusercontent.com/52677065/110501872-a1205f80-80c8-11eb-85ce-a86ae9a86649.png)

- Line missing after the intro text
- The text looks like it’s floating and somewhat awkwardly contained, so I suggest we bump up intro text to `lg` size, and allow it to take up 9 columns. This may need to change across all of the pages
- Should have 5 units of space after intro text and then 5 units of space after the `hr`  (above “Case Studies”)

## Cards
- Since the cards have a drop shadow they do not need a boarder 
Current branch:
![image](https://user-images.githubusercontent.com/52677065/110498946-c8296200-80c5-11eb-9781-7be0200a150a.png)

Proposed:
![image](https://user-images.githubusercontent.com/52677065/110499062-e4c59a00-80c5-11eb-9a54-bce6e5054e10.png)

## Quote
- Missing hr line after cards
- Should have 5 unites of space after cards before the line and 5 units after the line before the quote
- Could we increase the line-height of the quote to 1.35 (`lh(3)`) ? Note that the large quote mark should stay aligned with the top of the quote
- Quote attribution should start with an em dash (—), currently it's a hyphen (-)

## Agencies 
- Decrease Padding above Heading to 5 units
- Each agency list item should have 2 units of space below it
- Wondering if for the U.S. Air Force and for the U.S. army we ought to use their respective seals, in place of the logos to be more consistent with the other branches and agencies? 
[Army seal](https://en.wikipedia.org/wiki/United_States_Army#/media/File:Mark_of_the_United_States_Army.svg),  [Air Force seal ](https://en.wikipedia.org/wiki/United_States_Air_Force#/media/File:Mark_of_the_United_States_Air_Force.svg)

## Call to action
- Same as issue #3367 

## Summary Checklist
**Intro hero**
- [x] Changed based on #3374 

**Intro text**
- [x] Rule is added back in, is `gray-cool-10 `(`#dfe1e2`)
- [x] 5 units of space after intro text and then 5 units of space after the `hr`  (above “Case Studies”)

To be discussed: 
- [x] text is `lg` and takes up 9 columns instead of 8

**Cards**
- [ ] No border on the cards
- [ ] Rule after cards, with 5 units of space between the cards and the line
- [ ] Rule is is `gray-cool-10 `(`#dfe1e2`)

**Quote**
- [ ] 5 units of space between rule and quote
- [ ] Quote has line height of ~ 1.35 / `lh(3)`
- [ ] After line height change quote mark is lined up with top of quote
- [ ] Quote attribution starts with an em dash —

**Agencies**
- [ ] 5 units of space between heading and top of grey container
- [ ] Agency list item has 2 units of space below

To be decided:
- [ ] Replace U.S. Air Force and Army logos with seals 

**Call to Action**
- [x] Background color should be `#1C304A`  
- [x] Text is lg size
- [x] Button has background color `#00CFFF` and font-color `#1C304A`.  (can follow the [ACCENT COOL COLOR ](https://designsystem.digital.gov/components/button/)example for states)

**Comment by lauraGgit** [comment]
In pairing with @igorkorenfeld we'll update the block-quote styling to to @lauraponce's designs

**Comment by lauraGgit** [comment]
Going to swapping the agency logos into its own ticket. But the spacing will stay in.
