### ISSUE TITLE
Home page review

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/18f.gsa.gov#3378]
## Hero
![image](https://user-images.githubusercontent.com/52677065/110700816-6567c180-81be-11eb-9273-5909572d9eff.png)

- Background color of callout  is `#162e51` should be `#1C304A`
- Similar font chunkiness issue to #3367, let’s add `ls(1)` to letter spacing here
- There should be 3 units of space between the text and the button
- Button color should be `#00CFFF` as on the CTA for #3367 

## Quote
- Similar to #3376, could we change the line-height of this to `lh(3)`
- Attribution and quote mark are both `#00547a` should `#046B99`
- Attribution should start with an em dash (—) current a hyphen (-)

## We support
- Reduce space between quote and this section to 5 units
- Body text should be regular weight
- Line height should be 1.5

## Agencies 
- Reduce space above the header to 5 units
- Increase space below the header to 4 units
- Agency list items should have 2 units of space after each item
- See more agencies link should is `#00547a`, should be `#046B99`
- Chevron in the link should be smaller and vertically centered with the x-height of the text
- Reduce to 5 units of space after the link

Existing site: 
![image](https://user-images.githubusercontent.com/52677065/110701391-1d956a00-81bf-11eb-9be5-2776f39c992a.png)

Branch:
![image](https://user-images.githubusercontent.com/52677065/110701318-05bde600-81bf-11eb-92aa-1beb9f6de266.png)

## What can 18F do
- Reduce space above the header to 5 units

## Featured projects
- Reduce space above header to 5 units
- Increase space below the header to 4 units
- Add 0.5 units of space between the agency name and the project title
- Agency name should be `gray-cool-60`, looks like this is not being compiled correctly
- Chevron next to read more should be smaller and aligned with the x-height of the text
- Reduce space below cards to 5 units

## Recent blog posts
- Link text is `#00547a` should be `#046B99`
- Reduce space below tallest post preview to 5 units
- Chevron in the link should be smaller and vertically centered with the x-height of the text

## Summary checklist
**Hero**
- [ ] Background color of callout  is `#1C304A`
- [ ] Text has `ls(1)` to letter spacing
- [ ] 3 units of space between the text and the button
- [ ] Button has background color `#00CFFF` and font-color `#1C304A`.  (can follow the [ACCENT COOL COLOR ](https://designsystem.digital.gov/components/button/)example for states)

**Quote**
- [ ] Line-height is `lh(3)`
- [ ] Attribution and quote mark are `#046B99`
- [ ] Attribution starts with an em dash (—) 

**We support**
- [ ] 5 units of space above start of section
- [ ] Body text is regular weight
- [ ] Body line height should be 1.5

**Agencies** 
- [ ] Space above the header is 5 units
- [ ] Space below the header is 4 units
- [ ] Agency list items have 2 units of space after each item
- [ ]  See more agencies link is `#046B99`
- [ ]  Chevron in the link is smaller and vertically centered with the x-height of the text
- [ ]  5 units of space after the  see more link

**What can 18F do**
- [ ] Space above the header is 5 units

**Featured projects**
- [ ] Space above header is 5 units
- [ ] Space below the header is 4 units
- [ ] 0.5 units of space between the agency name and the project title
- [ ] Agency name is `gray-cool-60`
- [ ] Chevron next to read more is smaller and aligned with the x-height of the text
- [ ] Reduce space below cards to 5 units

**Recent blog posts**
- [ ] Link text is  `#046B99`
- [ ] Space below tallest post preview is 5 units
- [ ] Chevron in the link is smaller and vertically centered with the x-height of the text

**Comment by lauraGgit** [comment]
@igorkorenfeld let's hold off on this one since we will be redoing the designs per #3207 
 https://github.com/18F/18f.gsa.gov/issues/3207#issuecomment-774302822

one thing i'd be curious about before doing that is there are some color choices there that are more uswds than 18f - would you mind working with @lauraponce on ensuring that this mockup is aligned with the brand?
