### ISSUE TITLE
[EPIC] Migrate 18f.gsa.gov to 11ty

### ISSUE THREAD

**Issue by beechnut** [18F/18f.gsa.gov#3839]
We're doing it! The last migration of 18F sites away from Jekyll! (See https://github.com/18F/TLC-crew/issues/64)

All work will be done within the 18f.gsa.gov repo, off of the [replatforming-main](https://github.com/18F/18f.gsa.gov/tree/replatform-main) branch. This branch will be merged into main when ready.

**Acceptance criteria**
The 18F website, 18f.gsa.gov, is in production.

```[tasklist]
### Tasks
- [x] Decide whether to keep repo or merge with 18F/guides
- [ ] https://github.com/18F/18f.gsa.gov/issues/3842
- [ ] https://github.com/18F/18f.gsa.gov/issues/3843
- [ ] https://github.com/18F/18f.gsa.gov/issues/3844
- [ ] https://github.com/18F/18f.gsa.gov/issues/3845
- [ ] https://github.com/18F/18f.gsa.gov/issues/3847
- [ ] https://github.com/18F/18f.gsa.gov/issues/3854
- [ ] https://github.com/18F/18f.gsa.gov/issues/3857
- [ ] https://github.com/18F/18f.gsa.gov/issues/3867
- [ ] https://github.com/18F/18f.gsa.gov/issues/3859
- [ ] https://github.com/18F/18f.gsa.gov/issues/3866
- [ ] https://github.com/18F/18f.gsa.gov/issues/3855
- [ ] https://github.com/18F/18f.gsa.gov/issues/3875
- [ ] https://github.com/18F/18f.gsa.gov/issues/3849
- [ ] https://github.com/18F/18f.gsa.gov/issues/3861
- [ ] https://github.com/18F/18f.gsa.gov/issues/3848
- [x] Migrate blog pages and paginator (/blog/, /blog/page/2) #3852
- [x] Investigate and maybe migrate siteurl plugin (size: small, skills: dev)
- [x] Review all `testimonial-blockquote` and `markdown=1`
- [ ] https://github.com/18F/18f.gsa.gov/issues/3971
- [ ] https://github.com/18F/18f.gsa.gov/issues/3972
- [ ] https://github.com/18F/18f.gsa.gov/issues/3960
- [ ] https://github.com/18F/18f.gsa.gov/issues/3962
- [ ] https://github.com/18F/18f.gsa.gov/issues/3853
- [ ] https://github.com/18F/18f.gsa.gov/issues/3856
- [ ] https://github.com/18F/18f.gsa.gov/issues/3858
- [ ] https://github.com/18F/18f.gsa.gov/issues/4022
- [ ] https://github.com/18F/18f.gsa.gov/issues/3961
- [ ] https://github.com/18F/18f.gsa.gov/issues/3963
- [ ] https://github.com/18F/18f.gsa.gov/issues/3965
- [ ] https://github.com/18F/18f.gsa.gov/issues/3967
```

**Comment by beechnut** [comment]
@bpdesigns @cantsin

The right order for the rest of this work is:
- Complete #3858 and #3961 (increment goal)
- Then, after those are closed, complete #3963 and #3965 (increment goal, but not started until the first two are done)
- Then, publish the site with #3967 (probably next increment)

**Comment by beechnut** [comment]
We're done :)
