### ISSUE TITLE
🏁 Publish the new 18F site

### ISSUE THREAD

**Issue by beechnut** [18F/18f.gsa.gov#3967]
The 18F `main` branch has changed since we started the replatforming. I'm aware of several blog posts, at least one additional author, and some style changes relating to code blocks.

```[tasklist]
### Tasks
- [x] Build the Jekyll site and the 11ty site separately, then diff the two. Anything other than minor HTML changes should be raised for review
- [x] Resolve all major changes
- [x] Schedule a freeze on 18f.gsa.gov `main` while we prepare the merge
- [x] During the freeze, migrate new posts, author data, styles, and any content changed since May 23, 2024
- [x] Perform a final visual comparison, comparing all root pages (e.g. `/` (home), `/work-with-us`), a selection of old and new blog posts, and a selection of sub-pages
- [x] AFTER acceptance criteria is met, merge replatform-main --> main
```

```[tasklist]
### Acceptance criteria
- [x] A diff of old and new sites should show the sites to be equivalent in content
```

```[tasklist]
### Tasks
- [ ] https://github.com/18F/18f.gsa.gov/issues/4037
- [ ] https://github.com/18F/18f.gsa.gov/issues/4038
- [ ] https://github.com/18F/18f.gsa.gov/issues/4039
- [ ] https://github.com/18F/18f.gsa.gov/issues/4040
- [ ] https://github.com/18F/18f.gsa.gov/issues/4041
- [ ] https://github.com/18F/18f.gsa.gov/issues/4042
- [ ] https://github.com/18F/18f.gsa.gov/issues/4043
- [ ] https://github.com/18F/18f.gsa.gov/issues/4046
- [ ] https://github.com/18F/18f.gsa.gov/issues/4048
- [x] There are still a lot of blog posts with {{ site.baseurl }}s
- [x] Move authors
- [x] Move posts
- [x] Move blog post header styles
- [x] Move code block styles
- [x] Get pa11y working correctly (something's broken right now)
- [ ] https://github.com/18F/18f.gsa.gov/issues/4052
- [ ] https://github.com/18F/18f.gsa.gov/issues/4053
- [ ] https://github.com/18F/18f.gsa.gov/issues/4054
- [ ] https://github.com/18F/18f.gsa.gov/issues/4055
- [x] tags have double `//` in the url
- [x] `styled_container` layout still uses `page` incorrectly
- [x] footer is missing external link icons
- [x] subnav include is missing (on `/join`, `/about`, `/partnership-principles`)
- [x] `hide_footer_rule` still uses `page` incorrectly
- [x] `2015-08-12-18f-consulting-is-hiring` is unpublished and should be removed
- [x] `usa-current` does not show up in the menu for blog posts
- [x] pagination count is off by one: `Page 0 of 102`
- [x] missing blog image for "engineering at 10"
- [x] `/guides` has incorrect paragraph styling at the bottom
- [x] "Recent blog posts" is blank
- [x] Pages with `redirect_to` are not redirecting
- [x] we are showing some hero images when we shouldn't (example: /2014/05/11/18f-shows-what-is-possible-in-government-with-fbopen/)
- [x] Featured posts use related posts cache and actual posts, which have different title accesses (post.title vs post.data.title). Fix this in a way that's self-explanatory (no nil checks)
- [x] Add project-page layout back in, ensure projects pages follow it
- [x] Fix project page's related posts
- [x] blog posts have mismatched dates (file name vs front matter)
- [x] "Hacking bureaucracy" post has stray divs that break the page completely
- [x] published: false in projects pages (switch it to `eleventyExcludeFromCollections: true`)
- [x] text fixture "coming soon" is showing up as an actual post
- [x] Some blog images (gifs) do not animate properly
- [x] Test on mobile
```

**Comment by adunkman** [comment]
Assigning @beechnut since they moved it to in progress — @beechnut flag if you’d like someone else from TLC to pick this up.

**Comment by beechnut** [comment]
@cantsin Is that everything?? Is it time to freeze, migrate, and merge???

**Comment by cantsin** [comment]
It's Friday afternoon, traditionally the best time to merge new code 🎉 Surely nothing can go wrong over the weekend!

Yes, let's freeze. And plan to officially migrate/merge next week?

**Comment by beechnut** [comment]
Sounds good to me!

**Comment by beechnut** [comment]
Ok, here's where we're at: #4050 has the latest changes and gets us ready to release.

Things that aren't perfect:
- Code block styling doesn't have line numbers, and it'll take more time than I want to spend on that to get it ready and perfect. I'm ok leaving line numbers off, knowing I'll prioritize this in post-migration changes.
- There's still a lot of `site.baseurl`s. I thought that migrating this was essential for release, but it appears to be more of a nice-to-have. Whenever I check them, internal links work, assets render. I'm not anticipating any negative consequences from this.

With those noted in #3864 , how would we feel about flipping the switch and merging later today?

**Comment by beechnut** [comment]
Just merged #4058 and checked off the last 13 tasks! Thanks @cantsin for finding all of those and fixing most of them!

**Comment by cantsin** [comment]
so super excited to see all this work finally come to fruition 🎉 LETS DOOOO IT
